[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = ['npm ci --only=production']

[phases.build]
cmds = ['echo "API service build complete"']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'