[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm ci --omit=dev --ignore-scripts']

[phases.build]
cmds = ['echo "API service build complete"']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
# PORT is automatically assigned by Railway