[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Network configuration
[deploy.networking]
expose = true

# Environment variables
[deploy.env]
NODE_ENV = "production"
# PORT is automatically assigned by Railway - don't hardcode
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
JWT_SECRET = "${{ JWT_SECRET }}"
BCRYPT_ROUNDS = "12"