[build]
builder = "NIXPACKS"

[deploy]
startCommand = "next start -p 3001 -H 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Optimize build resources
[build.nixpacksConfigOverride]
memory = "3072"

# Network configuration
[deploy.networking]
expose = true

# Environment variables
[deploy.env]
NODE_ENV = "production"
PORT = "3001"
NEXT_TELEMETRY_DISABLED = "1"