[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Optimize build resources
[build.nixpacksConfigOverride]
memory = "3072"

# Network configuration
[deploy.networking]
expose = true

# Environment variables
[deploy.env]
NODE_ENV = "production"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"