[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
target = "production"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Optimize build resources
[build.nixpacksConfigOverride]
memory = "2048"

# Network configuration
[deploy.networking]
expose = true

# Environment variables
[deploy.env]
NODE_ENV = "production"
PORT = "3001"