[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Network configuration
[deploy.networking]
expose = true

# Environment variables
[deploy.env]
NODE_ENV = "production"
PORT = "3001"