[build]
builder = "NIXPACKS"

[deploy]
startCommand = "PORT=3001 node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Optimize build resources
[build.nixpacksConfigOverride]
memory = "3072"

# Network configuration
[deploy.networking]
expose = true

# Environment variables
[deploy.env]
NODE_ENV = "production"
PORT = "3001"
NEXT_TELEMETRY_DISABLED = "1"