[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nixPacksVersion = "1.21.0"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[deploy.env]
NODE_ENV = "production"
PORT = "3001"